window.facilities = [
  {
    no: "001",
    name: "ひらかたパーク",
    prefecture: "大阪府",
    city: "枚方市",
    genre: "遊園地",
    subGenre: "テーマパーク",
    distance: "約4km",
    driveTime: "約15分",
    toll: "0円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "入園料＋アトラクション料金",
    parking: "普通車2,000円／約1,100台",
    season: "通年",
    age: "2歳～",
    weather: "晴れ◎雨○",
    address: "大阪府枚方市枚方公園町1-1",
    hours: "営業日による",
    memo: "2歳から有料。屋内アトラクションあり",
    website: "https://www.hirakatapark.co.jp/"
  },
  {
    no: "002",
    name: "大阪城公園",
    prefecture: "大阪府",
    city: "大阪市中央区",
    genre: "公園",
    subGenre: "大型都市公園",
    distance: "約25km",
    driveTime: "約45分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府大阪市中央区大阪城",
    hours: "公園は常時利用",
    memo: "芝生・広場・散策向き",
    website: "https://www.osakacastlepark.jp/"
  },
  {
    no: "003",
    name: "海遊館",
    prefecture: "大阪府",
    city: "大阪市港区",
    genre: "水族館",
    subGenre: "大型水族館",
    distance: "約35km",
    driveTime: "約55分",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "年齢・日程で変動",
    parking: "天保山周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "雨◎",
    address: "大阪府大阪市港区海岸通1-1-10",
    hours: "日程で変動",
    memo: "雨の日に強い",
    website: "https://www.kaiyukan.com/"
  },
  {
    no: "004",
    name: "天王寺動物園",
    prefecture: "大阪府",
    city: "大阪市天王寺区",
    genre: "動物園",
    subGenre: "都市動物園",
    distance: "約35km",
    driveTime: "約55分",
    toll: "約1,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人500円／中学生以下無料",
    parking: "周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府大阪市天王寺区茶臼山町1-108",
    hours: "9:30～17:00等",
    memo: "動物園散策",
    website: "https://www.tennojizoo.jp/"
  },
  {
    no: "005",
    name: "ATCあそびマーレ",
    prefecture: "大阪府",
    city: "大阪市住之江区",
    genre: "室内遊び",
    subGenre: "室内遊園地",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "2歳～大人900円／土日祝1,100円／1歳600円／0歳無料",
    parking: "ATC駐車場",
    season: "通年",
    age: "0～12歳",
    weather: "雨◎",
    address: "大阪府大阪市住之江区南港北2-1-10 ITM棟5F",
    hours: "10:00～18:00",
    memo: "最終受付17:00。不定休",
    website: "https://atc-asobimare.jimdofree.com/"
  },
  {
    no: "006",
    name: "NIFREL",
    prefecture: "大阪府",
    city: "吹田市",
    genre: "ミュージアム",
    subGenre: "生きもの展示",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円～",
    indoorOutdoor: "屋内",
    admission: "料金は年齢・時期で変動",
    parking: "EXPOCITY駐車場",
    season: "通年",
    age: "幼児～",
    weather: "雨◎",
    address: "大阪府吹田市千里万博公園2-1 EXPOCITY内",
    hours: "日程で変動",
    memo: "年中無休。駐車2時間無料加算",
    website: "https://www.nifrel.jp/"
  },
  {
    no: "007",
    name: "万博記念公園",
    prefecture: "大阪府",
    city: "吹田市",
    genre: "公園",
    subGenre: "大型公園",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円～",
    indoorOutdoor: "屋外",
    admission: "大人450円／中学生以下無料",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府吹田市千里万博公園",
    hours: "9:30～17:00頃",
    memo: "2026年4月1日料金改定",
    website: "https://www.expo70-park.jp/"
  },
  {
    no: "008",
    name: "大阪府営深北緑地",
    prefecture: "大阪府",
    city: "大東市",
    genre: "公園",
    subGenre: "大型公園・遊具",
    distance: "約10km",
    driveTime: "約25分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "駐車場あり・有料",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府大東市深野北4",
    hours: "常時利用可",
    memo: "大型遊具あり",
    website: "https://www.fukakitaryokuchi.jp/"
  },
  {
    no: "009",
    name: "鶴見緑地",
    prefecture: "大阪府",
    city: "大阪市鶴見区",
    genre: "公園",
    subGenre: "大型公園",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府大阪市鶴見区緑地公園2-163",
    hours: "公園は常時利用",
    memo: "大型遊具・芝生",
    website: "https://www.tsurumi-ryokuchi.jp/"
  },
  {
    no: "010",
    name: "大阪市立自然史博物館",
    prefecture: "大阪府",
    city: "大阪市東住吉区",
    genre: "博物館",
    subGenre: "自然史博物館",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約500～1,000円",
    indoorOutdoor: "屋内",
    admission: "大人300円等",
    parking: "長居公園周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "雨◎",
    address: "大阪府大阪市東住吉区長居公園1-23",
    hours: "9:30～17:00",
    memo: "恐竜・動物・自然系",
    website: "https://www.omnh.jp/"
  },
  {
    no: "011",
    name: "堺市立ビッグバン",
    prefecture: "大阪府",
    city: "堺市南区",
    genre: "屋内遊び",
    subGenre: "科学・大型遊具",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "大人1,100円／中学生800円／小学生800円／3歳以上600円／3歳未満無料",
    parking: "駐車場あり",
    season: "通年",
    age: "0～",
    weather: "雨◎",
    address: "大阪府堺市南区茶山台1-9-1",
    hours: "10:00～17:00",
    memo: "月曜休館。春夏休み等は開館",
    website: "https://www.bigbang-sakai.jp/"
  },
  {
    no: "012",
    name: "池田市五月山動物園",
    prefecture: "大阪府",
    city: "池田市",
    genre: "動物園",
    subGenre: "小規模動物園",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外中心",
    admission: "無料",
    parking: "五月山公園駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府池田市綾羽2-5-33",
    hours: "要営業カレンダー確認",
    memo: "無料で動物を見られる",
    website: "https://www.ikedashi-kanko.jp/"
  },
  {
    no: "013",
    name: "五月山公園",
    prefecture: "大阪府",
    city: "池田市",
    genre: "公園",
    subGenre: "山・遊具",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府池田市綾羽2丁目",
    hours: "常時利用",
    memo: "動物園とセット向き",
    website: "https://www.ikedashi-kanko.jp/"
  },
  {
    no: "014",
    name: "箕面公園",
    prefecture: "大阪府",
    city: "箕面市",
    genre: "公園",
    subGenre: "自然公園・滝",
    distance: "約25km",
    driveTime: "約45分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "周辺有料駐車場",
    season: "春～秋",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府箕面市箕面公園",
    hours: "常時利用",
    memo: "滝まで散策。幼児は距離注意",
    website: "https://www.mino-park.jp/"
  },
  {
    no: "015",
    name: "服部緑地",
    prefecture: "大阪府",
    city: "豊中市",
    genre: "公園",
    subGenre: "大型公園・遊具",
    distance: "約25km",
    driveTime: "約45分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府豊中市服部緑地1-1",
    hours: "公園は常時利用",
    memo: "大型遊具・芝生",
    website: "https://hattori-ryokuchi.com/"
  },
  {
    no: "016",
    name: "浜寺公園",
    prefecture: "大阪府",
    city: "堺市西区",
    genre: "公園",
    subGenre: "大型公園・交通遊園",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府堺市西区浜寺公園町",
    hours: "公園は常時利用",
    memo: "大型遊具・交通遊園あり",
    website: "https://www.osaka-park.or.jp/parks/hamadera/"
  },
  {
    no: "017",
    name: "りんくう公園",
    prefecture: "大阪府",
    city: "泉佐野市",
    genre: "公園",
    subGenre: "海辺公園",
    distance: "約70km",
    driveTime: "約1時間20分",
    toll: "約1,500円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府泉佐野市りんくう往来北1-271",
    hours: "公園は常時利用",
    memo: "海・芝生・散策向き",
    website: "https://rinku.osaka-park.or.jp/"
  },
  {
    no: "018",
    name: "伊丹スカイパーク",
    prefecture: "兵庫県",
    city: "伊丹市",
    genre: "公園",
    subGenre: "飛行機・大型遊具",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約500円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "兵庫県伊丹市森本7-1-1",
    hours: "9:00～21:00",
    memo: "飛行機を間近で見られる",
    website: "https://www.itami-skypark.com/"
  },
  {
    no: "019",
    name: "久宝寺緑地",
    prefecture: "大阪府",
    city: "八尾市",
    genre: "公園",
    subGenre: "大型公園・遊具",
    distance: "約25km",
    driveTime: "約40分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府八尾市西久宝寺323",
    hours: "公園は常時利用",
    memo: "大型遊具・芝生",
    website: "https://www.toshi-kouen.jp/"
  },
  {
    no: "020",
    name: "安満遺跡公園",
    prefecture: "大阪府",
    city: "高槻市",
    genre: "公園",
    subGenre: "歴史公園・遊具",
    distance: "約12km",
    driveTime: "約25分",
    toll: "0円",
    indoorOutdoor: "屋外（一部屋内）",
    admission: "無料（一部施設有料）",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "大阪府高槻市八丁畷町12-3",
    hours: "公園は常時利用",
    memo: "広い芝生・遊具・カフェ",
    website: "https://www.seibu-la.co.jp/park/ama-sitepark/"
  },
  {
    no: "021",
    name: "大阪府民の森 ほしだ園地",
    prefecture: "大阪府",
    city: "交野市",
    genre: "自然公園",
    subGenre: "吊り橋・ハイキング",
    distance: "約10km",
    driveTime: "約25分",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "駐車場あり・有料",
    season: "春～秋",
    age: "幼児～（歩行力必要）",
    weather: "晴れ◎雨×",
    address: "大阪府交野市星田5019-1",
    hours: "9:30～16:30頃",
    memo: "星のブランコ。幼児は歩行距離注意",
    website: "https://o-wonderforest.com/hoshida/"
  },
  {
    no: "022",
    name: "堺・緑のミュージアム ハーベストの丘",
    prefecture: "大阪府",
    city: "堺市南区",
    genre: "農業公園",
    subGenre: "動物・体験",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人1,500円前後／子ども料金あり",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "大阪府堺市南区鉢ヶ峯寺2405-1",
    hours: "10:00～17:00頃",
    memo: "動物ふれあい・遊具・体験",
    website: "https://farm.or.jp/"
  },
  {
    no: "023",
    name: "クレヨンしんちゃん オラのあそべるゆめぱ～く くずは",
    prefecture: "大阪府",
    city: "枚方市",
    genre: "室内遊び",
    subGenre: "キッズパーク",
    distance: "約8km",
    driveTime: "約20分",
    toll: "0円",
    indoorOutdoor: "屋内",
    admission: "子ども時間制料金＋保護者料金",
    parking: "くずはモール駐車場",
    season: "通年",
    age: "0～12歳",
    weather: "雨◎",
    address: "大阪府枚方市楠葉花園町15-1 くずはモール内",
    hours: "10:00～19:00頃",
    memo: "屋内なので雨の日向き",
    website: "https://bandainamco-am.co.jp/kids/yumepaku/"
  },
  {
    no: "024",
    name: "神戸どうぶつ王国",
    prefecture: "兵庫県",
    city: "神戸市中央区",
    genre: "動物園",
    subGenre: "ふれあい動物園",
    distance: "約75km",
    driveTime: "約1時間30分",
    toll: "約2,000円",
    indoorOutdoor: "屋内外",
    admission: "大人2,200円／小学生1,200円／4～5歳500円／3歳以下無料",
    parking: "専用駐車場・有料",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "兵庫県神戸市中央区港島南町7-1-9",
    hours: "10:00～17:00",
    memo: "屋内エリアが多く雨でも行きやすい",
    website: "https://www.kobe-oukoku.com/"
  },
  {
    no: "025",
    name: "王子動物園",
    prefecture: "兵庫県",
    city: "神戸市灘区",
    genre: "動物園",
    subGenre: "動物園",
    distance: "約65km",
    driveTime: "約1時間20分",
    toll: "約1,500円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人600円／中学生以下無料",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "兵庫県神戸市灘区王子町3-1",
    hours: "9:00～17:00頃",
    memo: "動物園散策向き",
    website: "https://www.kobe-ojizoo.jp/"
  },
  {
    no: "026",
    name: "六甲山アスレチックパーク GREENIA",
    prefecture: "兵庫県",
    city: "神戸市灘区",
    genre: "アスレチック",
    subGenre: "大型アスレチック",
    distance: "約70km",
    driveTime: "約1時間30分",
    toll: "約2,000円",
    indoorOutdoor: "屋外",
    admission: "料金は季節等で変動",
    parking: "有料駐車場",
    season: "春～秋",
    age: "幼児～（施設により制限）",
    weather: "晴れ◎雨×",
    address: "兵庫県神戸市灘区六甲山町北六甲4512-98",
    hours: "10:00～17:00頃",
    memo: "年齢・身長制限あり",
    website: "https://www.rokkosan.com/greenia/"
  },
  {
    no: "027",
    name: "東条湖おもちゃ王国",
    prefecture: "兵庫県",
    city: "加東市",
    genre: "遊園地",
    subGenre: "おもちゃ・遊園地",
    distance: "約75km",
    driveTime: "約1時間30分",
    toll: "約2,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "入園料・フリーパスあり",
    parking: "有料駐車場",
    season: "通年",
    age: "0歳～",
    weather: "晴れ◎雨○",
    address: "兵庫県加東市黒谷1216",
    hours: "10:00～17:00頃",
    memo: "屋内おもちゃ館が多く幼児向き",
    website: "https://www.omochaoukoku.com/tojoko/"
  },
  {
    no: "028",
    name: "ネスタリゾート神戸",
    prefecture: "兵庫県",
    city: "三木市",
    genre: "リゾート",
    subGenre: "アクティビティ・プール",
    distance: "約75km",
    driveTime: "約1時間30分",
    toll: "約2,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "入場パス料金は時期で変動",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ○雨△",
    address: "兵庫県三木市細川町垂穂894-60",
    hours: "施設・季節で変動",
    memo: "プール等は季節営業",
    website: "https://nesta.co.jp/"
  },
  {
    no: "029",
    name: "京都市動物園",
    prefecture: "京都府",
    city: "京都市左京区",
    genre: "動物園",
    subGenre: "都市動物園",
    distance: "約35km",
    driveTime: "約55分",
    toll: "約1,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "一般750円／中学生以下無料",
    parking: "周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "京都府京都市左京区岡崎法勝寺町",
    hours: "9:00～17:00頃",
    memo: "幼児連れ定番",
    website: "https://zoo.city.kyoto.lg.jp/zoo/"
  },
  {
    no: "030",
    name: "京都水族館",
    prefecture: "京都府",
    city: "京都市下京区",
    genre: "水族館",
    subGenre: "都市型水族館",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "大人2,600円／小中学生1,400円／3歳以上900円",
    parking: "梅小路公園周辺有料駐車場",
    season: "通年",
    age: "3歳～",
    weather: "雨◎",
    address: "京都府京都市下京区観喜寺町35-1",
    hours: "10:00～18:00頃",
    memo: "2026年2月10日から料金改定",
    website: "https://www.kyoto-aquarium.com/"
  },
  {
    no: "031",
    name: "京都市青少年科学センター",
    prefecture: "京都府",
    city: "京都市伏見区",
    genre: "科学館",
    subGenre: "科学・プラネタリウム",
    distance: "約35km",
    driveTime: "約55分",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "一般520円／小学生100円／幼児無料",
    parking: "無料駐車場あり",
    season: "通年",
    age: "幼児～",
    weather: "雨◎",
    address: "京都府京都市伏見区深草池ノ内町13",
    hours: "9:00～17:00",
    memo: "プラネタリウムあり",
    website: "https://www.edu.city.kyoto.jp/science/"
  },
  {
    no: "032",
    name: "ニンテンドーミュージアム",
    prefecture: "京都府",
    city: "宇治市",
    genre: "ミュージアム",
    subGenre: "ゲーム・体験",
    distance: "約35km",
    driveTime: "約50分",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "大人3,300円／中高生2,200円／小学生1,100円／未就学児無料",
    parking: "駐車場は予約制等・要確認",
    season: "通年",
    age: "幼児～",
    weather: "雨◎",
    address: "京都府宇治市小倉町神楽田56",
    hours: "10:00～18:00",
    memo: "日時指定チケット。予約推奨",
    website: "https://museum.nintendo.com/"
  },
  {
    no: "033",
    name: "滋賀農業公園ブルーメの丘",
    prefecture: "滋賀県",
    city: "日野町",
    genre: "農業公園",
    subGenre: "動物・遊具・体験",
    distance: "約55km",
    driveTime: "約1時間10分",
    toll: "約1,500円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人1,500円前後／子ども料金あり",
    parking: "無料駐車場",
    season: "春～秋中心",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "滋賀県蒲生郡日野町西大路843",
    hours: "10:00～17:00頃",
    memo: "動物ふれあい・遊具・体験",
    website: "https://www.blumenooka.jp/"
  },
  {
    no: "034",
    name: "うだ・アニマルパーク",
    prefecture: "奈良県",
    city: "宇陀市",
    genre: "動物園・公園",
    subGenre: "動物ふれあい",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "0円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "無料",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "奈良県宇陀市大宇陀小附75-1",
    hours: "9:00～17:00頃",
    memo: "無料で動物とふれあえる",
    website: "https://www.pref.nara.jp/1839.htm"
  },
  {
    no: "035",
    name: "馬見丘陵公園",
    prefecture: "奈良県",
    city: "北葛城郡河合町",
    genre: "公園",
    subGenre: "大型公園・遊具",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "0円",
    indoorOutdoor: "屋外",
    admission: "無料",
    parking: "無料駐車場あり",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "奈良県北葛城郡河合町佐味田2202",
    hours: "公園は常時利用可",
    memo: "大型遊具・季節の花",
    website: "https://www.pref.nara.jp/1714.htm"
  },
  {
    no: "036",
    name: "奈良公園",
    prefecture: "奈良県",
    city: "奈良市",
    genre: "公園",
    subGenre: "鹿・歴史公園",
    distance: "約45km",
    driveTime: "約1時間",
    toll: "約1,000円",
    indoorOutdoor: "屋外",
    admission: "無料（一部施設有料）",
    parking: "周辺有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "奈良県奈良市登大路町",
    hours: "24時間",
    memo: "鹿とのふれあい。鹿せんべいあり",
    website: "https://www3.pref.nara.jp/park/"
  },
  {
    no: "037",
    name: "生駒山上遊園地",
    prefecture: "奈良県",
    city: "生駒市",
    genre: "遊園地",
    subGenre: "山上遊園地",
    distance: "約25km",
    driveTime: "約45分",
    toll: "約1,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "入園無料・アトラクション有料",
    parking: "駐車場有料",
    season: "春～秋中心",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "奈良県生駒市菜畑町2312-1",
    hours: "10:00～17:00頃",
    memo: "入園無料。乗り物は別料金",
    website: "https://www.ikomasanjou.com/"
  },
  {
    no: "038",
    name: "奈良健康ランド はしゃきっズ",
    prefecture: "奈良県",
    city: "天理市",
    genre: "室内遊び",
    subGenre: "キッズパーク",
    distance: "約35km",
    driveTime: "約50分",
    toll: "約1,000円",
    indoorOutdoor: "屋内",
    admission: "施設利用料金あり・年齢等で変動",
    parking: "無料駐車場",
    season: "通年",
    age: "0～12歳",
    weather: "雨◎",
    address: "奈良県天理市嘉幡町600-1",
    hours: "10:00～21:00頃",
    memo: "温浴施設と併設。雨の日向き",
    website: "https://www.narakenkoland.net/"
  },
  {
    no: "039",
    name: "奈良県営まほろば健康パーク",
    prefecture: "奈良県",
    city: "大和郡山市",
    genre: "公園",
    subGenre: "遊具・プール・運動施設",
    distance: "約30km",
    driveTime: "約45分",
    toll: "0円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "無料（一部施設有料）",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "奈良県大和郡山市宮堂町310",
    hours: "施設ごとに異なる",
    memo: "大型遊具・夏季プール",
    website: "https://www.pref.nara.jp/47986.htm"
  },
  {
    no: "040",
    name: "神崎農村公園 ヨーデルの森",
    prefecture: "兵庫県",
    city: "神河町",
    genre: "農業公園",
    subGenre: "動物・体験",
    distance: "約105km",
    driveTime: "約1時間50分",
    toll: "約2,500円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人1,200円／4歳以上700円",
    parking: "無料駐車場・約800台",
    season: "春～秋中心",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "兵庫県神崎郡神河町猪篠1868",
    hours: "10:00～17:00頃",
    memo: "動物ふれあい・芝滑り等",
    website: "https://yodel-forest.jp/"
  },
  {
    no: "041",
    name: "滋賀県立びわ湖こどもの国",
    prefecture: "滋賀県",
    city: "高島市",
    genre: "公園",
    subGenre: "大型遊具・キャンプ",
    distance: "約80km",
    driveTime: "約1時間30分",
    toll: "約1,500円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "無料（一部施設有料）",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "滋賀県高島市安曇川町北船木2981",
    hours: "9:00～17:00頃",
    memo: "大型遊具・湖畔・宿泊施設",
    website: "https://www.biwa.ne.jp/~kodomo92/"
  },
  {
    no: "042",
    name: "淡路ワールドパーク ONOKORO",
    prefecture: "兵庫県",
    city: "淡路市",
    genre: "遊園地",
    subGenre: "テーマパーク",
    distance: "約150km",
    driveTime: "約2時間20分",
    toll: "約3,500円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "入園料あり・乗り物別料金",
    parking: "無料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "兵庫県淡路市塩田新島8-5",
    hours: "10:00～17:30頃",
    memo: "ミニチュア世界・遊具・乗り物",
    website: "https://www.onokoro.jp/"
  },
  {
    no: "043",
    name: "神戸市立六甲山牧場",
    prefecture: "兵庫県",
    city: "神戸市灘区",
    genre: "牧場",
    subGenre: "動物ふれあい",
    distance: "約75km",
    driveTime: "約1時間30分",
    toll: "約2,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人600円前後／小中学生200円前後",
    parking: "有料駐車場",
    season: "通年",
    age: "幼児～",
    weather: "晴れ◎雨△",
    address: "兵庫県神戸市灘区六甲山町中一里山1-1",
    hours: "9:00～17:00頃",
    memo: "羊・ヤギなどとふれあえる",
    website: "https://rokkosan.jp/"
  },
  {
    no: "044",
    name: "ワールド牧場",
    prefecture: "大阪府",
    city: "河南町",
    genre: "牧場",
    subGenre: "動物ふれあい",
    distance: "約55km",
    driveTime: "約1時間10分",
    toll: "約1,000円",
    indoorOutdoor: "屋外中心（一部屋内）",
    admission: "大人1,600円前後／子ども料金あり",
    parking: "無料駐車場",
    season: "春～秋中心",
    age: "幼児～",
    weather: "晴れ◎雨○",
    address: "大阪府南河内郡河南町白木1456-2",
    hours: "10:00～17:30頃",
    memo: "火曜休園が基本。季節で変動",
    website: "https://www.worldranch.co.jp/"
  }
];