const facilities = [
  {
    no: "001",
    name: "ひらかたパーク",
    prefecture: "大阪府",
    city: "枚方市",
    genre: "遊園地",
    subgenre: "アトラクション・動物・季節イベント",
    distance: "約5km",
    driveTime: "約15分",
    toll: "0円",
    indoorOutdoor: "屋外中心",
    price: "大人2,000円・小学生1,200円・2歳〜未就学児1,200円",
    parking: "あり・2,000円",
    season: "通年",
    age: "2歳〜",
    weather: "☀️晴れ向き・一部雨対応",
    address: "大阪府枚方市枚方公園町1-1",
    hours: "日によって異なる",
    memo: "2歳から入園有料。約1,100台の駐車スペースあり。雨でも利用できるアトラクションあり",
    website: "https://www.hirakatapark.co.jp/"
  },

  {
    no: "002",
    name: "大阪城公園",
    prefecture: "大阪府",
    city: "大阪市中央区",
    genre: "公園",
    subgenre: "歴史・遊具・散策",
    distance: "約25km",
    driveTime: "約45分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料施設）",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府大阪市中央区大阪城1-1",
    hours: "24時間（一部施設除く）",
    memo: "広大な公園。散歩や遊具、季節のイベントなど",
    website: ""
  },

  {
    no: "003",
    name: "海遊館",
    prefecture: "大阪府",
    city: "大阪市港区",
    genre: "水族館",
    subgenre: "海の生き物",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府大阪市港区海岸通1-1-10",
    hours: "日により異なる",
    memo: "雨の日の定番。館内中心で3歳でも楽しみやすい",
    website: "https://www.kaiyukan.com/"
  },

  {
    no: "004",
    name: "天王寺動物園",
    prefecture: "大阪府",
    city: "大阪市天王寺区",
    genre: "動物園",
    subgenre: "動物",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋外中心",
    price: "有料",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府大阪市天王寺区茶臼山町1-108",
    hours: "9:30〜17:00等",
    memo: "動物を見ながら歩いて楽しめる",
    website: ""
  },

  {
    no: "005",
    name: "キッズプラザ大阪",
    prefecture: "大阪府",
    city: "大阪市北区",
    genre: "博物館",
    subgenre: "体験・科学",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋内",
    price: "大人1,400円・幼児500円等",
    parking: "なし（周辺有料P）",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府大阪市北区扇町2-1-7",
    hours: "9:30〜17:00",
    memo: "3〜5歳料金あり。子どもが体験しながら遊べる",
    website: ""
  },

  {
    no: "006",
    name: "レゴランド・ディスカバリー・センター大阪",
    prefecture: "大阪府",
    city: "大阪市港区",
    genre: "室内遊び場",
    subgenre: "レゴ・体験",
    distance: "約30km",
    driveTime: "約50分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり",
    season: "通年",
    age: "3〜10歳",
    weather: "☔雨OK",
    address: "大阪府大阪市港区海岸通1-1-10 天保山マーケットプレース3F",
    hours: "日により異なる",
    memo: "対象年齢3〜10歳。日時指定予約が必要",
    website: ""
  },

  {
    no: "007",
    name: "ATCあそびマーレ",
    prefecture: "大阪府",
    city: "大阪市住之江区",
    genre: "室内遊び場",
    subgenre: "室内遊園地",
    distance: "約35km",
    driveTime: "約55分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府大阪市住之江区南港北2-1-10",
    hours: "9:00〜20:00等",
    memo: "大型の室内遊び場。天候を気にせず遊べる",
    website: ""
  },

  {
    no: "008",
    name: "NIFREL",
    prefecture: "大阪府",
    city: "吹田市",
    genre: "水族館",
    subgenre: "生き物・体験",
    distance: "約15km",
    driveTime: "約30分",
    toll: "約0円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府吹田市千里万博公園2-1 EXPOCITY内",
    hours: "10:00〜18:00等",
    memo: "生き物を近くで見られる屋内施設",
    website: ""
  },

  {
    no: "009",
    name: "万博記念公園",
    prefecture: "大阪府",
    city: "吹田市",
    genre: "公園",
    subgenre: "自然・遊具",
    distance: "約15km",
    driveTime: "約30分",
    toll: "約0円",
    indoorOutdoor: "屋外",
    price: "公園入園有料",
    parking: "あり",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府吹田市千里万博公園1-1",
    hours: "9:30〜17:00等",
    memo: "広大な公園。遊具や自然を楽しめる",
    website: ""
  },

  {
    no: "010",
    name: "大阪府営深北緑地",
    prefecture: "大阪府",
    city: "大東市",
    genre: "公園",
    subgenre: "遊具・広場",
    distance: "約7km",
    driveTime: "約15分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府大東市深野北4-284",
    hours: "常時利用可",
    memo: "自宅から近めで普段使いしやすい公園",
    website: ""
  },

  {
    no: "011",
    name: "鶴見緑地",
    prefecture: "大阪府",
    city: "大阪市鶴見区",
    genre: "公園",
    subgenre: "自然・遊具",
    distance: "約12km",
    driveTime: "約25分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料）",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府大阪市鶴見区緑地公園2-163",
    hours: "常時利用可",
    memo: "広い芝生や遊具があり家族向け",
    website: ""
  },

  {
    no: "012",
    name: "咲くやこの花館",
    prefecture: "大阪府",
    city: "大阪市鶴見区",
    genre: "植物園",
    subgenre: "植物・自然",
    distance: "約12km",
    driveTime: "約25分",
    toll: "0円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府大阪市鶴見区緑地公園2-163",
    hours: "10:00〜17:00",
    memo: "大温室があり雨の日でも楽しみやすい",
    website: ""
  },

  {
    no: "013",
    name: "大阪市立自然史博物館",
    prefecture: "大阪府",
    city: "大阪市東住吉区",
    genre: "博物館",
    subgenre: "恐竜・自然科学",
    distance: "約25km",
    driveTime: "約40分",
    toll: "0円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府大阪市東住吉区長居公園1-23",
    hours: "9:30〜17:00等",
    memo: "恐竜や動物・自然について学べる",
    website: ""
  },

  {
    no: "014",
    name: "長居公園",
    prefecture: "大阪府",
    city: "大阪市東住吉区",
    genre: "公園",
    subgenre: "遊具・自然",
    distance: "約25km",
    driveTime: "約40分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料）",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府大阪市東住吉区長居公園1-1",
    hours: "常時利用可",
    memo: "広い公園で子ども向け施設も複数",
    website: ""
  },

  {
    no: "015",
    name: "大泉緑地",
    prefecture: "大阪府",
    city: "堺市北区",
    genre: "公園",
    subgenre: "遊具・自然",
    distance: "約30km",
    driveTime: "約45分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府堺市北区金岡町128",
    hours: "常時利用可",
    memo: "大型遊具や広場があり一日遊びやすい",
    website: ""
  },

  {
    no: "016",
    name: "大仙公園",
    prefecture: "大阪府",
    city: "堺市堺区",
    genre: "公園",
    subgenre: "古墳・自然・遊具",
    distance: "約35km",
    driveTime: "約50分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料）",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府堺市堺区百舌鳥夕雲町2-204",
    hours: "常時利用可",
    memo: "古墳周辺の広い公園。散歩にも向く",
    website: ""
  },

  {
    no: "017",
    name: "堺市立ビッグバン",
    prefecture: "大阪府",
    city: "堺市南区",
    genre: "児童館",
    subgenre: "体験・遊具",
    distance: "約35km",
    driveTime: "約50分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋内",
    price: "有料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府堺市南区茶山台1-9-1",
    hours: "10:00〜17:00",
    memo: "大型遊具や体験展示がある子ども向け施設",
    website: ""
  },

  {
    no: "018",
    name: "カップヌードルミュージアム 大阪池田",
    prefecture: "大阪府",
    city: "池田市",
    genre: "博物館",
    subgenre: "食育・体験",
    distance: "約20km",
    driveTime: "約35分",
    toll: "約0円",
    indoorOutdoor: "屋内",
    price: "無料（一部体験有料）",
    parking: "なし・周辺P",
    season: "通年",
    age: "3歳〜",
    weather: "☔雨OK",
    address: "大阪府池田市満寿美町8-25",
    hours: "9:30〜16:30等",
    memo: "オリジナルカップヌードル作りなど体験型",
    website: ""
  },

  {
    no: "019",
    name: "池田市五月山動物園",
    prefecture: "大阪府",
    city: "池田市",
    genre: "動物園",
    subgenre: "動物",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府池田市綾羽2-5-33",
    hours: "9:15〜16:45等",
    memo: "無料で動物を見られるのが魅力",
    website: ""
  },

  {
    no: "020",
    name: "五月山公園",
    prefecture: "大阪府",
    city: "池田市",
    genre: "公園",
    subgenre: "遊具・自然",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府池田市綾羽2-5-33",
    hours: "常時利用可",
    memo: "動物園とセットで遊びやすい",
    website: ""
  },

  {
    no: "021",
    name: "箕面公園",
    prefecture: "大阪府",
    city: "箕面市",
    genre: "公園",
    subgenre: "自然・滝",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "周辺有料P",
    season: "春・夏・秋・冬",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府箕面市箕面公園",
    hours: "常時利用可",
    memo: "滝までの散策がメイン。3歳は歩ける範囲で楽しむのがおすすめ",
    website: ""
  },

  {
    no: "022",
    name: "服部緑地",
    prefecture: "大阪府",
    city: "豊中市",
    genre: "公園",
    subgenre: "遊具・自然",
    distance: "約20km",
    driveTime: "約35分",
    toll: "0円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料）",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府豊中市服部緑地1-1",
    hours: "常時利用可",
    memo: "大型公園で遊具・広場が充実",
    website: ""
  },

  {
    no: "023",
    name: "浜寺公園",
    prefecture: "大阪府",
    city: "堺市西区",
    genre: "公園",
    subgenre: "遊具・交通遊園",
    distance: "約40km",
    driveTime: "約55分",
    toll: "約0〜1,000円",
    indoorOutdoor: "屋外",
    price: "無料（一部有料）",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府堺市西区浜寺公園町",
    hours: "常時利用可",
    memo: "大型遊具や交通遊園など子ども向け要素が多い",
    website: ""
  },

  {
    no: "024",
    name: "岸和田城",
    prefecture: "大阪府",
    city: "岸和田市",
    genre: "観光",
    subgenre: "城・公園",
    distance: "約50km",
    driveTime: "約1時間",
    toll: "約0〜1,500円",
    indoorOutdoor: "屋外中心",
    price: "城内有料",
    parking: "あり・有料",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府岸和田市岸城町9-1",
    hours: "10:00〜17:00等",
    memo: "城周辺の公園と組み合わせて遊べる",
    website: ""
  },

  {
    no: "025",
    name: "りんくう公園",
    prefecture: "大阪府",
    city: "泉佐野市",
    genre: "公園",
    subgenre: "海・散策",
    distance: "約65km",
    driveTime: "約1時間15分",
    toll: "約1,000円〜",
    indoorOutdoor: "屋外",
    price: "無料",
    parking: "周辺有料P",
    season: "通年",
    age: "3歳〜",
    weather: "☀️晴れ向き",
    address: "大阪府泉佐野市りんくう往来北1-271",
    hours: "常時利用可",
    memo: "海を見ながら散歩でき、飛行機も見られる",
    website: ""
  }
];